steps:
  # ✅ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
        '.'
      ]

  # ✅ Run local unit tests (before deployment)
  - name: 'python'
    entrypoint: 'python3'
    args: ['-m', 'unittest', 'discover', '-s', 'test']
    env:
      - 'APP_URL=http://localhost'

  # ✅ Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
      ]

  # ✅ Initialize Terraform
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args: ['init']

  # ✅ Destroy existing infrastructure (clean before deploy)
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args: ['destroy', '-auto-approve']

  # ✅ Apply new infrastructure
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']

  # ✅ Capture the external IP and save it for tests
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        terraform output -raw web_server_external_ip > ip.txt
        cat ip.txt

  # ✅ Run tests against the deployed app
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        EXTERNAL_IP=$(cat ip.txt)
        echo "Running tests on deployed app at http://$EXTERNAL_IP"
        APP_URL=http://$EXTERNAL_IP python3 -m unittest discover -s test

timeout: 1800s
