options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Cleanup existing GCP resources (best-effort)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧹 Cleaning up existing GCP resources..."
        set -e
        gcloud compute instances delete public-web-server --zone=us-central1-a --quiet || true
        gcloud compute networks subnets delete public-subnet --region=us-central1 --quiet || true
        gcloud compute networks subnets delete private-subnet --region=us-central1 --quiet || true
        gcloud compute firewall-rules delete allow-http-https --quiet || true
        gcloud compute firewall-rules delete allow-ssh-from-iap --quiet || true
        gcloud compute networks delete my-vpc --quiet || true

  # Step 2: Terraform init
  - name: 'hashicorp/terraform:1.6.6'
    args: ['init']

  # Step 3: Terraform validate
  - name: 'hashicorp/terraform:1.6.6'
    args: ['validate']

  # Step 4: Terraform apply
  - name: 'hashicorp/terraform:1.6.6'
    args: ['apply', '-auto-approve', '-var-file=terraform.tfvars']

  # Step 5: Run tests
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔍 Running tests..."
        chmod +x ./run_test.sh
        ./run_test.sh

timeout: 1200s  # 20 minutes
