options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 🚀 Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
        '.'
      ]

  # 🚀 Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
      ]

  # ⚙️ Terraform init
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init

  # ⚙️ Terraform plan (optional sanity check)
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform validate

  # ⚙️ Terraform import using script (absolute path + ls debug)
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "📂 Listing files in /workspace:"
        ls -la /workspace
        chmod +x /workspace/import.sh
        /workspace/import.sh

  # ⚙️ Terraform apply
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform apply -auto-approve

  # ✅ Run deploy test
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x /workspace/run_test.sh
        /workspace/run_test.sh

timeout: 1800s
