options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 🚀 Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
        '.'
      ]

  # 🚀 Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
      ]

  # ⚙️ Terraform init (uses GCS backend configured in code)
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init

  # ⚙️ Terraform import (only if not already in state)
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        PROJECT_ID=graphite-store-463414-p2

        terraform state list | grep google_compute_network.vpc_network || \
          terraform import google_compute_network.vpc_network my-vpc

        terraform state list | grep google_compute_subnetwork.public_subnet || \
          terraform import google_compute_subnetwork.public_subnet us-central1/public-subnet

        terraform state list | grep google_compute_subnetwork.private_subnet || \
          terraform import google_compute_subnetwork.private_subnet us-central1/private-subnet

        terraform state list | grep google_compute_firewall.allow_http_https || \
          terraform import google_compute_firewall.allow_http_https projects/${PROJECT_ID}/global/firewalls/allow-http-https

        terraform state list | grep google_compute_firewall.allow_ssh_from_iap || \
          terraform import google_compute_firewall.allow_ssh_from_iap projects/${PROJECT_ID}/global/firewalls/allow-ssh-from-iap

  # ⚙️ Terraform apply
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform apply -auto-approve

  # ✅ Run deploy test
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x run_test.sh
        ./run_test.sh

timeout: 1800s
