steps:
  # ✅ Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
        '.'
      ]

  # ✅ Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
      ]

  # ✅ (Optional) Run tests
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install requests numpy --quiet
        python test/test_deploy.py || exit 1

  # ✅ Deploy to VM using gcloud and deploy.sh
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x deploy.sh
        ./deploy.sh

images:
  - 'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY

# Grant permissions for Artifact Registry pull on VM
serviceAccount: terraform-sa@graphite-store-463414-p2.iam.gserviceaccount.com
