steps:

# 1️⃣ Run automated tests
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "🚀 Running automated tests..."
      chmod +x test.sh
      ./test.sh

# 2️⃣ Download SSH keys + SCP files
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "⬇️ Downloading SSH keys from Cloud Storage..."
      gsutil cp gs://graphite-store-463414-p2_cloudbuild/cloudbuild_vm_key /workspace/cloudbuild_vm_key
      gsutil cp gs://graphite-store-463414-p2_cloudbuild/cloudbuild_vm_key.pub /workspace/cloudbuild_vm_key.pub
      chmod 400 /workspace/cloudbuild_vm_key

      echo "📌 VM IP is ${_VMIP}"

      echo "⏳ Sleeping 60 seconds for VM readiness..."
      sleep 60

      echo "⏳ Attempting SCP with static SSH key..."
      for i in {1..5}; do
        scp -i /workspace/cloudbuild_vm_key -o StrictHostKeyChecking=no \
          -r ./app/* cloudbuild@${_VMIP}:/var/www/html && break || {
            echo "⚠️ Attempt $i failed. Retrying in 10s..."
            sleep 10
          }
      done

# 3️⃣ Restart Nginx + Enable Cloud Logging agent
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "📌 VM IP is ${_VMIP}"

      echo "🔄 Restarting Nginx and enabling Cloud Logging agent..."
      ssh -i /workspace/cloudbuild_vm_key -o StrictHostKeyChecking=no cloudbuild@${_VMIP} \
      "sudo systemctl restart nginx && \
       sudo apt-get update && \
       sudo apt-get install -y google-fluentd && \
       sudo systemctl enable google-fluentd && \
       sudo systemctl restart google-fluentd"

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
