options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
        '.'
      ]

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
      ]

  # Terraform init with GCS backend
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'terraform'
    args: ['init']

  # Terraform apply
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']

  # Deploy test: get external IP + run test
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching external IP..."
        IP=$(terraform output -raw web_server_external_ip)
        echo "IP: $IP"
        ./deploy_test.sh "$IP"

timeout: 1800s
