options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
      '.'
    ]

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
    ]

  # Terraform init
  - name: 'hashicorp/terraform'
    dir: 'gcp-webapp-cicd'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init

  # Terraform apply
  - name: 'hashicorp/terraform'
    dir: 'gcp-webapp-cicd'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform apply -auto-approve
