options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
      '.'
    ]

  # Run unit tests inside Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'run',
      '--rm',
      'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
      'python3', '-m', 'unittest', 'discover', '-s', 'test'
    ]

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
    ]

  # Terraform init
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'terraform'
    args: ['init']

  # Terraform destroy
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'terraform'
    args: ['destroy', '-auto-approve']

  # Terraform apply
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']

  # Capture external IP
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        terraform output -raw web_server_external_ip > ip.txt
        cat ip.txt

  # Run deploy test
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        terraform output -raw web_server_external_ip > ip.txt
        EXTERNAL_IP=$(cat ip.txt)
        echo "External IP is $EXTERNAL_IP"
        curl -f http://$EXTERNAL_IP || exit 1

timeout: 1800s
