options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧹 Cleaning up..."
        gcloud compute instances delete public-web-server --zone=us-central1-a --quiet || true
        gcloud compute networks subnets delete public-subnet --region=us-central1 --quiet || true
        gcloud compute networks subnets delete private-subnet --region=us-central1 --quiet || true
        gcloud compute firewall-rules delete allow-http-https --quiet || true
        gcloud compute firewall-rules delete allow-ssh-from-iap --quiet || true
        gcloud compute networks delete my-vpc --quiet || true

  - name: 'hashicorp/terraform:1.6.6'
    args: ['init']

  - name: 'hashicorp/terraform:1.6.6'
    args: ['validate']

  - name: 'hashicorp/terraform:1.6.6'
    args: ['apply', '-auto-approve']

  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform output -raw web_server_external_ip > /workspace/ip.txt
        echo "Captured IP: $(cat /workspace/ip.txt)"

  - name: 'curlimages/curl:7.87.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        IP=$(cat /workspace/ip.txt)
        echo "Running test on http://$IP"
        chmod +x ./run_test.sh
        ./run_test.sh $IP

timeout: 1200s
