options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'run',
      '--rm',
      'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
      'python3', '-m', 'unittest', 'discover', '-s', 'test'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
    ]

  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'terraform'
    args: ['init']

  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        IP=$(terraform output -raw web_server_external_ip)
        echo "Testing deployed app at http://$IP"
        curl -f http://$IP || (echo 'App test failed!' && exit 1)

timeout: 1800s
