steps:

# 1️⃣ Run automated tests
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "🚀 Running automated tests..."
      chmod +x test.sh
      ./test.sh

# 2️⃣ Sleep + SCP app files using static SSH key
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "⏳ Sleeping 60 seconds for VM readiness..."
      sleep 60

      echo "⏳ Attempting SCP with static SSH key..."
      for i in {1..5}; do
        gcloud compute scp \
          --zone=us-central1-a \
          --ssh-key-file=/workspace/cloudbuild_vm_key \
          --recurse \
          ./app/* \
          cloudbuild@web-server:/var/www/html && break || {
            echo "⚠️ Attempt $i failed. Retrying in 10s..."
            sleep 10
          }
      done

# 3️⃣ Restart Nginx to serve the new app
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh \
        --zone=us-central1-a \
        --ssh-key-file=/workspace/cloudbuild_vm_key \
        cloudbuild@web-server \
        --command="sudo systemctl restart nginx"

timeout: 900s
