options:
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: tf-cache
      path: /workspace/.terraform

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
      '.'
    ]

  - name: 'python'
    entrypoint: 'python3'
    args: ['-m', 'unittest', 'discover', '-s', 'test']
    env:
      - 'APP_URL=http://localhost'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
    ]

  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'terraform'
    args: ['init']
    volumes:
      - name: tf-cache
        path: /workspace/.terraform

  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'terraform'
    args: ['destroy', '-auto-approve']
    volumes:
      - name: tf-cache
        path: /workspace/.terraform

  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']
    volumes:
      - name: tf-cache
        path: /workspace/.terraform

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        terraform output -raw web_server_external_ip > ip.txt
        cat ip.txt

timeout: 1800s
