steps:
  # Step 1: Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app'
      ]

  # Step 2: Cleanup existing infra
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🧹 Cleaning up existing GCP resources..."
        gcloud compute instances delete web-server --zone=us-central1-a --quiet || echo "✅ No VM found or already deleted"
        gcloud compute firewall-rules delete allow-http-https --quiet || echo "✅ No firewall allow-http-https found"
        gcloud compute networks subnets delete private-subnet --region=us-central1 --quiet || echo "✅ No private subnet found"
        gcloud compute networks delete my-vpc --quiet || echo "✅ No VPC found"

  # Step 3: Terraform init
  - name: 'hashicorp/terraform:1.6.6'
    args: ['init']

  # Step 4: Terraform validate
  - name: 'hashicorp/terraform:1.6.6'
    args: ['validate']

  # Step 5: Force unlock (in case a stale lock exists)
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        LOCK_ID=$(terraform force-unlock -force 2>&1 | grep 'ID:' | awk '{print $2}')
        if [ -n "$LOCK_ID" ]; then
          terraform force-unlock -force $LOCK_ID || true
        else
          echo "✅ No lock found to force unlock"
        fi

  # Step 6: Terraform apply
  - name: 'hashicorp/terraform:1.6.6'
    args: ['apply', '-auto-approve']

  # Step 7: Run app tests
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching external IP..."
        IP=$(terraform output -raw web_server_external_ip)
        echo "External IP: $IP"
        APP_URL="http://$IP"
        APP_URL=$APP_URL python3 -m unittest test/test_deploy.py

images:
  - 'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app'
