options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 🚀 Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
        '.'
      ]

  # 🚀 Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
      ]

  # ⚙️ Terraform init
  - name: 'hashicorp/terraform:1.6.6'
    dir: '/workspace'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init

  # ⚙️ Terraform import using script
  - name: 'hashicorp/terraform:1.6.6'
    dir: '/workspace'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "📂 Current directory contents:"
        ls -la
        chmod +x import.sh
        ./import.sh

  # ⚙️ Terraform apply
  - name: 'hashicorp/terraform:1.6.6'
    dir: '/workspace'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform apply -auto-approve

  # ✅ Run deploy test
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: '/workspace'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x run_test.sh
        ./run_test.sh

timeout: 1800s
