options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 🚀 Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest',
        '.'
      ]

  # 🚀 Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
      ]

  # ⚙️ Terraform init
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init

  # ⚠️ Terraform destroy existing infra (FREE UP resources)
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🔥 Destroying previous infrastructure to free up resources..."
        terraform destroy -auto-approve || echo "Nothing to destroy or destroy failed. Continuing."

  # ⚙️ Terraform apply fresh infra
  - name: 'hashicorp/terraform:1.6.6'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🚀 Applying fresh infrastructure..."
        terraform apply -auto-approve

  # ✅ Run deploy test
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x /workspace/run_test.sh
        /workspace/run_test.sh

timeout: 1800s
