steps:

# 1️⃣ Run automated tests — must pass to continue
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "🚀 Running automated tests..."
      chmod +x test.sh
      ./test.sh
  # If this fails, the build will stop and no further steps will run.

# 2️⃣ Cleanup: Check for existing VM and delete if found
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "🔍 Checking for existing VM..."
      VM_EXISTS=$(gcloud compute instances list --filter="name=web-server" --format="value(name)")
      if [ "$VM_EXISTS" != "" ]; then
        echo "⚠️ Existing VM found: $VM_EXISTS — deleting..."
        gcloud compute instances delete web-server --zone=us-central1-a --quiet
      else
        echo "✅ No existing VM to delete."
      fi

# 3️⃣ Create a fresh VM with Nginx + Cloud Logging agent
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'compute', 'instances', 'create', 'web-server',
      '--zone=us-central1-a',
      '--machine-type=e2-micro',
      '--subnet=public-subnet',
      '--tags=http-server,https-server',
      '--image-family=debian-11',
      '--image-project=debian-cloud',
      '--metadata=startup-script=sudo apt update && sudo apt install -y nginx google-fluentd && sudo systemctl enable nginx && sudo systemctl start nginx && sudo systemctl enable google-fluentd && sudo systemctl start google-fluentd'
    ]

# 4️⃣ Copy app files to the VM
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'compute', 'scp',
      '--zone=us-central1-a',
      '--recurse',
      './app/*',
      'web-server:/var/www/html'
    ]

# 5️⃣ Restart Nginx to serve the new app
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'compute', 'ssh',
      '--zone=us-central1-a',
      'web-server',
      '--command=sudo systemctl restart nginx'
    ]

timeout: 900s
