steps:

# 1️⃣ Run automated tests
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "🚀 Running automated tests..."
      chmod +x test.sh
      ./test.sh

# 2️⃣ Download SSH keys + Sleep + SCP files
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "⬇️ Downloading SSH keys from Cloud Storage..."
      gsutil cp gs://graphite-store-463414-p2_cloudbuild/cloudbuild_vm_key /workspace/cloudbuild_vm_key
      gsutil cp gs://graphite-store-463414-p2_cloudbuild/cloudbuild_vm_key.pub /workspace/cloudbuild_vm_key.pub
      chmod 400 /workspace/cloudbuild_vm_key
      chmod 400 /workspace/cloudbuild_vm_key.pub

      echo "⏳ Sleeping 60 seconds for VM readiness..."
      sleep 60

      echo "⏳ Attempting SCP with static SSH key..."
      for i in {1..5}; do
        gcloud compute scp \
          --zone=us-central1-a \
          --ssh-key-file=/workspace/cloudbuild_vm_key \
          --recurse \
          ./app/* \
          cloudbuild@web-server:/var/www/html && break || {
            echo "⚠️ Attempt $i failed. Retrying in 10s..."
            sleep 10
          }
      done

# 3️⃣ Restart Nginx + Enable Cloud Logging agent
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "🔄 Restarting Nginx and enabling Cloud Logging agent..."
      gcloud compute ssh \
        --zone=us-central1-a \
        --ssh-key-file=/workspace/cloudbuild_vm_key \
        cloudbuild@web-server \
        --command="sudo systemctl restart nginx && \
                   sudo apt-get update && \
                   sudo apt-get install -y google-fluentd && \
                   sudo systemctl enable google-fluentd && \
                   sudo systemctl restart google-fluentd"

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
