steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest', '.']

- name: 'docker'
  entrypoint: 'docker'
  args: ['run', '-d', '--rm', '-p', '80:80', 'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest']

- name: 'python:3.9'
  entrypoint: 'python'
  args: ['test/test_deploy.py']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'compute'
    - 'ssh'
    - 'web-server'
    - '--zone=us-central1-a'
    - '--command=sudo docker pull us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest && sudo docker stop my-app || true && sudo docker rm my-app || true && sudo docker run -d --name my-app -p 8080:80 us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
