steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'
      - '.'

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest'

  # Run tests: spin up container, test, clean up
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker run -d --name test-app -p 8080:80 us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest
        sleep 5  # give it time to start
        pip install requests
        python -m unittest discover -s test
        docker stop test-app
        docker rm test-app

  # Deploy to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'web-server'
      - '--zone=us-central1-a'
      - '--command'
      - |
        sudo docker pull us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest && \
        sudo docker stop my-app || true && \
        sudo docker rm my-app || true && \
        sudo docker run -d --name my-app -p 8080:80 us-central1-docker.pkg.dev/graphite-store-463414-p2/my-repo/my-app:latest

options:
  logging: CLOUD_LOGGING_ONLY
