options:
  logging: CLOUD_LOGGING_ONLY

steps:

# 1️⃣ Run automated tests — must pass to continue
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "🚀 Running automated tests..."
      chmod +x test.sh
      ./test.sh
      TEST_EXIT_CODE=$$?
      if [ $$TEST_EXIT_CODE -ne 0 ]; then
        echo "❌ Tests failed. Exiting build."
        exit $$TEST_EXIT_CODE
      fi
      echo "✅ All tests passed."

# 2️⃣ Deploy app files to the VM with retry logic for SSH readiness
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "⏳ Waiting for SSH to become ready..."
      for i in {1..5}; do
        if gcloud compute scp --zone=us-central1-a --recurse ./app/* web-server:/var/www/html; then
          echo "✅ File copy succeeded"
          exit 0
        else
          echo "⚠️ Attempt $$i failed. Retrying in 10s..."
          sleep 10
        fi
      done
      echo "❌ File copy failed after retries"
      exit 1

# 3️⃣ Restart Nginx to serve the new app
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'compute', 'ssh',
      '--zone=us-central1-a',
      'web-server',
      '--command=sudo systemctl restart nginx'
    ]

timeout: 900s
