options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1️⃣ Automated tests
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "🚀 Running automated tests..."
      chmod +x test.sh
      ./test.sh
      if [ $? -ne 0 ]; then
        echo "❌ Tests failed!"
        exit 1
      fi
      echo "✅ All tests passed."

# 2️⃣ Wait for VM and copy app files
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "⏳ Sleeping 60 seconds for VM readiness..."
      sleep 60
      for i in {1..5}; do
        echo "⏳ Attempt $$i: copying files..."
        if gcloud compute scp --zone=us-central1-a --recurse ./app/* web-server:/var/www/html; then
          echo "✅ Files copied successfully!"
          exit 0
        else
          echo "⚠️ Attempt $$i failed. Retrying in 10s..."
          sleep 10
        fi
      done
      echo "❌ SCP failed after retries"
      exit 1

# 3️⃣ Restart Nginx
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'compute', 'ssh',
      '--zone=us-central1-a',
      'web-server',
      '--command=sudo systemctl restart nginx'
    ]

timeout: 900s
